site_name: Kibibyte
site_url: https://kibibyte.in
site_author: Nadeem Siddique
site_description: >-
  Solving niche problems

# Repository
# repo_name: purplecandy
# repo_url: https://github.com/purplecandy/

# Copyright
copyright: Copyright &copy; 2017 - 2023 Nadeem Siddique - Kibibyte

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  favicon: assets/favicon-32x32.png
  logo: assets/transparent.png

# Plugins
plugins:
  - awesome-pages
  - glightbox
  - tags:
      tags_name_property: Togs
      tags_file: tags.md 
  - blog:
      enabled: true
      blog_dir: blog
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
# hooks:
#   - material/.overrides/hooks/translations.py

# Customization
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.
    actions:
      - accept
      - reject
      - manage
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: G-3HYT9Y4TBR
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purplecandy
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/389690594185838594
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purlpe_candy
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/expressionsofnadeem
extra_css:
  - stylesheets/extra.css
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Thoughts: 'tags/#thoughts'
  - Garage: garage.md
      # - 2023:
      #     - blog/posts/building-a-news-letters-for-engineers.md
      #     - blog/posts/beginers-guide-on-securing-your-linux-server.md
      # - 2022:
      #     - blog/posts/how-to-choose-the-right-database-for-your-project.md
      # - 2021:
      #     - blog/posts/why-web-framework-benchmarks-are-misleading.md
      # - 2020:
      #     - blog/posts/how-to-install-postgress-on-server.md
      
      
      
      
